# Generated by Django 4.1.7 on 2023-03-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aciklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=0, max_digits=20)),
                ('miktar', models.DecimalField(decimal_places=0, max_digits=20)),
                ('tarih', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('resim', models.FileField(default='static/images/avatar.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tarih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odenen_proje', models.CharField(max_length=30, null=True)),
                ('odenen_santiye', models.CharField(max_length=30, null=True)),
                ('odenen_tutar', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('tarih', models.CharField(max_length=13, null=True)),
                ('aciklama', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Santiye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20)),
                ('miktar', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('hakedis_sebebi', models.CharField(max_length=100, null=True)),
                ('hakedis_tarihi', models.DateField(null=True)),
                ('resim', models.FileField(default='static/images/avatar.jpg', upload_to='')),
                ('araclar', models.ManyToManyField(to='myapp.arac')),
                ('baglanti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.proje')),
            ],
        ),
        migrations.AddField(
            model_name='proje',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sirket'),
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('cinsiyet', models.CharField(max_length=10)),
                ('yas', models.DecimalField(decimal_places=0, max_digits=4)),
                ('baslamaTarih', models.DateField()),
                ('resim', models.FileField(default='static/images/avatar.jpg', upload_to='')),
                ('birim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.santiye')),
            ],
        ),
        migrations.CreateModel(
            name='Hakedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=20)),
                ('tutar', models.DecimalField(decimal_places=0, max_digits=20)),
                ('tarih', models.DateField()),
                ('odeme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.santiye')),
                ('odemeproje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.proje')),
            ],
        ),
    ]
